name: 🤖 CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0

      - name: 🔣 Fetching inputs…
        run: ./inputs.main.kts
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}

      - run: ./gradlew build

      - name: Archive JUnit HTML report
        uses: actions/upload-artifact@v3
        with:
          name: junit-html
          path: build/reports/tests/test

      - name: Archive JUnit XML report
        uses: actions/upload-artifact@v3
        with:
          name: junit-xml
          path: build/test-results/test/**.xml
